### ISSUE TITLE
How to get manual CAPTCHA working

### ISSUE THREAD

**Issue by ArgDave** [Noctem/Monocle#122]
I have installed the selenium package and the Chromedriver, but cannot work out how to get manual CAPTCHAs going. I thought it might be `python solve_captchas.py` but there is obviously more to it! Please help.

**Comment by manolomanila** [comment]
There is nothing more really. Make sure Chromedriver is in the same folder than _solve_captchas.py_ tho

**Comment by ArgDave** [comment]
Thanks for the response. I get:
`C:\Users\Dave\Monocle>python solve_captchas.py
Traceback (most recent call last):
  File "solve_captchas.py", line 6, in <module>
    from pogo_async.session import Session
ImportError: cannot import name 'Session'`.
I am running under Windows 7....do I need to set Chrome as my default browser?

**Comment by manolomanila** [comment]
Noctem already fixed that, a pull should solve it: `git pull https://github.com/Noctem/Monocle.git`

**Comment by ArgDave** [comment]
Great, that changed things, but now I get:
`C:\Users\Dave\Monocle>python solve_captchas.py
Traceback (most recent call last):
  File "solve_captchas.py", line 178, in <module>
    loop.run_until_complete(main())
  File "C:\Program Files\Python\lib\asyncio\base_events.py", line 466, in run_un
til_complete
    return future.result()
  File "solve_captchas.py", line 69, in main
    manager.connect()
  File "C:\Program Files\Python\lib\multiprocessing\managers.py", line 489, in c
onnect
    conn = Client(self._address, authkey=self._authkey)
  File "C:\Program Files\Python\lib\multiprocessing\connection.py", line 485, in
 Client
    c = PipeClient(address)
  File "C:\Program Files\Python\lib\multiprocessing\connection.py", line 686, in
 PipeClient
    _winapi.WaitNamedPipe(address, 1000)
FileNotFoundError: [WinError 2] The system cannot find the file specified`.

Any ideas?

**Comment by manolomanila** [comment]
No clue. Just in case I would: `pip install -r requirements.txt --upgrade`

also for optional requirements.

**Comment by Noctem** [comment]
Did you set a `MANAGER_ADDRESS` in config? You should generally leave that commented out unless you have a reason you need to change it.

**Comment by ArgDave** [comment]
I've tried playing around with `MANAGER_ADDRESS` but still get errors. I have not changed `AUTHKEY` but should I? Also, I assume I should change `MANAGER_ADDRESS = r'\\.\pipe\monocle'` to something to match my setup. I did try setting up a UBUNTU VirtualBox on my Win 7 machine and my Mac and still not luck. I think I am cursed!

**Comment by ArgDave** [comment]
OK. I gave up on my Win7 install and with VitualBoxes and I have now installed Ubuntu 16 onto a PC. It's all back and running but still cannot do manual captchas. I get a `connection refused Errno 111`. I assume I need to open a port somewhere?

**Comment by ArgDave** [comment]
Didn't realise that I needed to have scan.py running already to then run solve_captcha.py. Works fine now!
